/**
 * Picks the one dimension to point a student at, and supplies the fixed
 * copy that goes with it.
 *
 * The copy here is deliberately NOT generated by the AI. Two reasons:
 * lib/ai/client.ts filters model output through BANNED_PATTERNS, which
 * blocks much of this phrasing outright; and a claim about what Saati can
 * do for someone's wellbeing is marketing copy that a human should review
 * once, not text a model reimprovises on every page load. The AI writes
 * the therapeutic summary; this file writes the invitation. Keeping the
 * two apart is what stops the pitch leaking into the care language.
 *
 * Wording approved by the founder 2026-08-28.
 */

import type { ReportData } from "./getReportData";

/** "who5", or one of the five core PERMA domain keys as used throughout
 * lib/scoring/perma.ts and PERMA_CORE_DOMAIN_LABELS (P/E/R/M/A). */
export type FocusAreaKey = "who5" | "P" | "E" | "R" | "M" | "A";

export interface FocusArea {
  key: FocusAreaKey;
  /** Human label for the dimension, as shown to the student. */
  label: string;
  /** What the score is describing, in the student's terms. */
  plainDescription: string;
  /** How Saati addresses this specific area. */
  saatiOffer: string;
  percentageScore: number;
}

const COPY: Record<
  FocusAreaKey,
  { label: string; plainDescription: string; saatiOffer: string }
> = {
  who5: {
    label: "day-to-day wellbeing",
    plainDescription:
      "how you have been feeling in yourself over the last two weeks — your energy, your mood, how rested you feel.",
    saatiOffer:
      "Saati can help you improve this. It checks in with you daily, notices how your mood moves over time, and gives you short grounding practices to use in the moments that are hardest.",
  },
  P: {
    label: "emotional wellbeing",
    plainDescription:
      "how much of your ordinary day carries some warmth, ease or enjoyment in it.",
    saatiOffer:
      "Saati can help you improve your emotional wellbeing. Through daily companion conversations and guided practices drawn from thirty years of contemplative training, it helps you build back the small good moments that make a day feel liveable.",
  },
  E: {
    label: "engagement",
    plainDescription:
      "how absorbed you get in what you are doing — whether time disappears, or drags.",
    saatiOffer:
      "Saati can help you improve your engagement. It works with you on attention and focus, and helps you find your way back into the activities that genuinely absorb you.",
  },
  R: {
    label: "relationships",
    plainDescription:
      "how supported and connected you feel to the people around you.",
    saatiOffer:
      "Saati can help you improve your relationships. It is deliberately built to move you toward people rather than away from them — helping you prepare for hard conversations, and encouraging the calls and visits that matter.",
  },
  M: {
    label: "sense of meaning",
    plainDescription:
      "how much your days feel like they are pointing somewhere you care about.",
    saatiOffer:
      "Saati can help you improve your sense of meaning. Its Find Your Ikigai conversation is built for exactly this — an unhurried, resumable exploration of what matters to you and why.",
  },
  A: {
    label: "sense of accomplishment",
    plainDescription:
      "how often you finish something and feel you actually got somewhere.",
    saatiOffer:
      "Saati can help you improve your sense of accomplishment. It helps you set goals that fit the week you are actually having, and notices your progress with you rather than keeping score.",
  },
};

/**
 * The lowest-scoring dimension, since that is the one with the most room.
 *
 * WHO-5 only wins when it is below its own published threshold — it
 * measures something broader than a single PERMA domain, so pointing a
 * student at "day-to-day wellbeing" is only useful when the validated
 * instrument itself flags it. Otherwise a specific PERMA domain gives them
 * something they can actually act on.
 *
 * Ties resolve to whichever comes first in the PERMA_ORDER below, so the
 * same scores always produce the same focus area — a student refreshing
 * the page must never be told a different thing.
 */
const PERMA_ORDER: FocusAreaKey[] = ["P", "E", "R", "M", "A"];

export function selectFocusArea(report: ReportData): FocusArea {
  const candidates = PERMA_ORDER.map((key) => ({
    key,
    percentageScore:
      report.perma.find((d) => d.domain === key)?.percentageScore ?? 100,
  }));

  let lowest = candidates[0];
  for (const candidate of candidates) {
    if (candidate.percentageScore < lowest.percentageScore) {
      lowest = candidate;
    }
  }

  const key: FocusAreaKey =
    report.belowThreshold && report.who5.percentageScore < lowest.percentageScore
      ? "who5"
      : lowest.key;

  const percentageScore =
    key === "who5" ? report.who5.percentageScore : lowest.percentageScore;

  return { key, percentageScore, ...COPY[key] };
}
