/**
 * Results are generated by one request and emailed by a later, separate one
 * (results are shown before the address is asked for). The reflection therefore
 * makes a round trip through the browser.
 *
 * Without a signature that turns /api/ikigai/deliver into an open relay: anyone
 * could POST an arbitrary body and an arbitrary recipient and have it sent from
 * our verified domain. So the generate step signs the reflection and the deliver
 * step refuses anything it did not itself produce.
 *
 * This does NOT rate-limit. Someone can still replay a valid pair to re-send
 * themselves the same reflection. That is low-harm and left as known work.
 */

import { createHmac, timingSafeEqual } from "node:crypto";
import { CIRCLE_KEYS, type IkigaiResult } from "./reflection";

/**
 * Any of these secrets works — we only need a stable server-side value the
 * client never sees. In production at least one is always set. If none is,
 * signing returns null and delivery refuses: the page still works, it just
 * cannot email. Fail closed, not open.
 */
function secret(): string | null {
  return (
    process.env.IKIGAI_SIGNING_SECRET ||
    process.env.RESEND_API_KEY ||
    process.env.OPENAI_API_KEY ||
    null
  );
}

/** Stable serialisation — key order must not depend on object construction. */
function canonical(result: IkigaiResult): string {
  return JSON.stringify([
    result.centre ?? "",
    ...CIRCLE_KEYS.map((k) => result.circles?.[k] ?? ""),
    result.thread ?? "",
    result.step ?? "",
  ]);
}

export function signResult(result: IkigaiResult): string | null {
  const key = secret();
  if (!key) return null;
  return createHmac("sha256", key).update(canonical(result)).digest("hex");
}

export function verifyResult(result: IkigaiResult, token: unknown): boolean {
  if (typeof token !== "string" || token.length === 0) return false;
  const expected = signResult(result);
  if (!expected) return false;
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(token, "utf8");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}
